spring:
  # datasource 数据源配置内容
  datasource:
    username: root
    password: hejianfei1998
    url: jdbc:mysql://127.0.0.1:3306/meetsystem?useUnicode=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 200  # 最大连接数
      minimum-idle: 100 # 最小空闲数
      connection-timeout: 2000 # 获取连接超时时间； 默认30s
      pool-name: my-test-hikari # 连接池名称
      idle-timeout: 600000 # 空闲超时时间；默认是十分钟；空闲时间超过设定时间则会被回收
      auto-commit: true # 是否自动提交
      max-lifetime: 1800000 # 最大存活时间，默认30分钟
      # connection-test-query: SELECT 1  # 连接数据库后测试语句
      validation-timeout: 1000 #

# mybatis 配置内容
mybatis:
  #  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.example.mybatis.entity # 配置数据库实体包路径
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰